config/routes.rb
Rails.application.routes.draw do
  resources :records
  devise_for :users
  resources :states
  resources :roles
  resources :beneficiaries
  resources :objectives
  resources :classifications
  resources :zones


  get 'welcome/index'

  get 'beneficiaries/', to:'beneficiaries#index', as:'beneficiarios'

  get 'classifications/', to: 'classifications#index'

  get 'objectives/', to: 'objectives#index'

  get 'records/', to: 'records#index'

  get 'roles', to: 'roles#index'

  get 'states', to: 'states#index'

  get 'zones', to: 'zones#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/objective.rb
class Objective < ApplicationRecord
  belongs_to :zone
  belongs_to :classification
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:update,:mostrar,:index,:crear,:eliminar,:editar,:nuevo]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      params.require(:objective).permit(:texto, :zone_id, :classification_id)
    end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <section class="content invoice">
    <%= form_for(objective) do |f| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibido guardar este Objetivo:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
  <div class="form-group">
  <div class="field">
    <%= f.label :texto %>
  </div>
  <div class="field">
    <%= f.text_area :texto %>
  </div>
  </div>

  <div class="form-group">
  <div class="field">
    <%= f.label :zone_id, "Area " %>
     <%= collection_select( :objective, :zone_id, Zone.all, :id, :nombre, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
  </div>

  <div class="form-group">
  <div class="field">
    <%= f.label :classification_id, "Clasificacion " %>
    <%= collection_select( :objective, :classification_id, Classification.all, :id, :nombre, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
  </div>

  <div class="form-group">
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>
</div>
  </section>
</body>
</html>

app/views/objectives/edit.html.erb
<h1>Editar Objetivos</h1>

<%= render 'form', objective: @objective %>


<%= link_to 'Volver', objectives_path %>

app/views/objectives/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <h1>Objetivos</h1>
      </div>
      <div class="row">
        <span class="pull-left glyphicon glyphicon-plus"><%= link_to 'Crear Objetivo', new_objective_path %></span>
      </div>
    </section>
<% end %>

<section class="content invoice">
<div class="table-responsive">
<table border="1" class="table table-striped" >
  <thead>
    <tr>
      <th>Texto</th>
      <th>Area</th>
      <th>Clasificación</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= objective.texto %></td>
        <td><%= objective.zone.nombre %></td>
        <td><%= objective.classification.nombre %></td>
        <td><span class="glyphicon glyphicon-pencil" aria-hidden="true"><%= link_to 'Editar', edit_objective_path(objective) %></td>
        <td><span class="glyphicon glyphicon-trash" aria-hidden="true"><%= link_to 'Eliminar', objective, method: :delete, data: { confirm: '¿Esta seguro de eliminar este objetivo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>

app/views/objectives/new.html.erb
<h1>Nuevo Objetivo</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Volver', objectives_path %>

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Texto:</strong>
  <%= @objective.texto %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @objective.zone.nombre %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @objective.classification.nombre %>
</p>


<%= link_to 'Editar', edit_objective_path(@objective) %> |
<%= link_to 'Volver', objectives_path %>