config/routes.rb
Rails.application.routes.draw do
  resources :records
  devise_for :users
  resources :states
  resources :roles
  resources :beneficiaries
  resources :objectives
  resources :classifications
  resources :zones


  get 'welcome/index'

  get 'beneficiaries/', to:'beneficiaries#index', as:'beneficiarios'

  get 'classifications/', to: 'classifications#index'

  get 'objectives/', to: 'objectives#index'

  get 'records/', to: 'records#index'

  get 'roles', to: 'roles#index'

  get 'states', to: 'states#index'

  get 'zones', to: 'zones#index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :beneficiary
  belongs_to :state
  belongs_to :objective
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:update,:mostrar,:index,:crear,:eliminar,:editar,:nuevo]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
    respond_to do |format|
     format.html
     format.pdf do
       pdf = RecordPdf.new(@record)
       send_data pdf.render, filename: "Historial_#{@record.beneficiary.nombre}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end 
    end
  end


  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:user_id, :beneficiary_id, :state_id, :objective_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Crea un Historial</title>
</head>
<body>
  <section class="content invoice">
      <%= form_for(record) do |f| %>
        <% if record.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(record.errors.count, "error") %> Prohibido guardar este Historial :</h2>

            <ul>
            <% record.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

    <div class="row">
    <div class="form-group">
  <div class="field">
    <%= f.label :user_id, "Usuario" %>
     <%= collection_select( :record, :user_id, User.all, :id, :nombre, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
  </div>
     <div class="form-group">

  <div class="field">
    <%= f.label :beneficiary_id, "Beneficiario" %>
     <%= collection_select( :record, :beneficiary_id, Beneficiary.all, :id, :nombre, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
</div>
   <div class="form-group">
  <div class="field">
    <%= f.label :state_id, "Estado" %>
    <%= collection_select( :record, :state_id, State.all, :id, :nombre, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
  </div>
   <div class="form-group">
  <div class="field">
    <%= f.label :objective_id, "Objetivo" %>
     <%= collection_select( :record, :objective_id, Objective.all, :id, :texto, { :multiple => false }, { :class => "my-custom-class" } ) %>
  </div>
  </div>
   <div class="form-group">
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
  </div>

<% end %>
</div>
</section>
</body>
</html>

app/views/records/edit.html.erb
<h1>Editar Historial</h1>

<%= render 'form', record: @record %>

<%= link_to 'Volver', records_path %>

app/views/records/index.html.erb
<% content_for :content_header do %>
    <section class="content-header">
      <p id="notice"><%= notice %></p>
      <div class="row">
        <h1>Historial</h1>
      </div>
      <div class="row">
        <span class="pull-left glyphicon glyphicon-plus"><%= link_to 'Crear Historial', new_record_path %></span>
      </div>
    </section>
<% end %>

<section class="content invoice">
<div class="table-responsive">
<table border="1" class="table table-striped">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Beneficiario</th>
      <th>Estado</th>
      <th>Objetivo</th>
      <th>Generar PDF</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
  </thead>

  <tbody>
    <input type="text" id="busqueda" />
    <div id="resultado"></div>
    
    <% @records.each do |record| %>
      <tr>
        <td><%= record.user.nombre %></td>
        <td><%= record.beneficiary.nombre %></td>
        <td><%= record.state.nombre %></td>
        <td><%= record.objective.texto %></td>
        <td><span class="glyphicon glyphicon-list-alt" aria-hidden="true"><%= link_to "PDF", record_path(record, format: "pdf")%></td>
        <td><span class="glyphicon glyphicon-pencil" aria-hidden="true"><%= link_to 'Editar', edit_record_path(record) %></td>
        <td><span class="glyphicon glyphicon-trash" aria-hidden="true"><%= link_to 'Eliminar', record, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>
<br>

app/views/records/new.html.erb
<h1>Nuevo Historial</h1>

<%= render 'form', record: @record %>

<%= link_to 'Volver', records_path %>

app/views/records/show.html.erb
<table>
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @record.user.to_s %>
</p>

<p>
  <strong>Beneficiary:</strong>
  <%= @record.beneficiary.to_s %>
</p>

<p>
  <strong>State:</strong>
  <%= @record.state.to_s %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @record.objective.to_s %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>
</table>

<p><%= link_to "PDF", record_path(@record, format: "pdf")%></p>

<%= link_to 'Editar', edit_record_path(@record) %> |
<%= link_to 'Volver', records_path %>
<%= link_to "PDF", record_path(@record, format: "pdf")%>
</body>
</html>